In [523]:
import pandas as pd
from sklearn.utils import *
from sklearn.datasets import load_iris
from sklearn.metrics import *
import warnings
from sklearn.ensemble import RandomForestRegressor

train = pd.read_csv('C:/Users/USER/Desktop/poweruser_python/train.csv')
test = pd.read_csv('C:/Users/USER/Desktop/poweruser_python/test.csv')

In [524]:
train.head()

,id,hour,hour_bef_temperature,hour_bef_precipitation,hour_bef_windspeed,hour_bef_humidity,hour_bef_visibility,hour_bef_ozone,hour_bef_pm10,hour_bef_pm2.5,count
0,3,20,16.3,1.0,1.5,89.0,576.0,0.027,76.0,33.0,49.0
1,6,13,20.1,0.0,1.4,48.0,916.0,0.042,73.0,40.0,159.0
2,7,6,13.9,0.0,0.7,79.0,1382.0,0.033,32.0,19.0,26.0
3,8,23,8.1,0.0,2.7,54.0,946.0,0.040,75.0,64.0,57.0
4,9,18,29.5,0.0,4.8,7.0,2000.0,0.057,27.0,11.0,431.0

In [525]:
train.info() # 10컬럼, 1459행, int + float type, 결측값 있음

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      1459 non-null   int64
 1   hour                    1459 non-null   int64
 2   hour_bef_temperature    1457 non-null   float64
 3   hour_bef_precipitation  1457 non-null   float64
 4   hour_bef_windspeed      1450 non-null   float64
 5   hour_bef_humidity       1457 non-null   float64
 6   hour_bef_visibility     1457 non-null   float64
 7   hour_bef_ozone          1383 non-null   float64
 8   hour_bef_pm10           1369 non-null   float64
 9   hour_bef_pm2.5          1342 non-null   float64
 10  count                   1459 non-null   float64
dtypes: float64(9), int64(2)
memory usage: 125.5 KB

In [526]:
train.describe()

,id,hour,hour_bef_temperature,hour_bef_precipitation,hour_bef_windspeed,hour_bef_humidity,hour_bef_visibility,hour_bef_ozone,hour_bef_pm10,hour_bef_pm2.5,count
count,1459.000000,1459.000000,1457.000000,1457.000000,1450.000000,1457.000000,1457.000000,1383.000000,1369.000000,1342.000000,1459.000000
mean,1105.914325,11.493489,16.717433,0.031572,2.479034,52.231297,1405.216884,0.039149,57.168736,30.327124,108.563400
std,631.338681,6.922790,5.239150,0.174917,1.378265,20.370387,583.131708,0.019509,31.771019,14.713252,82.631733
min,3.000000,0.000000,3.100000,0.000000,0.000000,7.000000,78.000000,0.003000,9.000000,8.000000,1.000000
25%,555.500000,5.500000,12.800000,0.000000,1.400000,36.000000,879.000000,0.025500,36.000000,20.000000,37.000000
50%,1115.000000,11.000000,16.600000,0.000000,2.300000,51.000000,1577.000000,0.039000,51.000000,26.000000,96.000000
75%,1651.000000,17.500000,20.100000,0.000000,3.400000,69.000000,1994.000000,0.052000,69.000000,37.000000,150.000000
max,2179.000000,23.000000,30.000000,1.000000,8.000000,99.000000,2000.000000,0.125000,269.000000,90.000000,431.000000

In [527]:
test.head()

,id,hour,hour_bef_temperature,hour_bef_precipitation,hour_bef_windspeed,hour_bef_humidity,hour_bef_visibility,hour_bef_ozone,hour_bef_pm10,hour_bef_pm2.5
0,0,7,20.7,0.0,1.3,62.0,954.0,0.041,44.0,27.0
1,1,17,30.0,0.0,5.4,33.0,1590.0,0.061,49.0,36.0
2,2,13,19.0,1.0,2.1,95.0,193.0,0.020,36.0,28.0
3,4,6,22.5,0.0,2.5,60.0,1185.0,0.027,52.0,38.0
4,5,22,14.6,1.0,3.4,93.0,218.0,0.041,18.0,15.0

In [528]:
test.info() # 9컬럼, 715행, int + float type, 결측값 있음

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 715 entries, 0 to 714
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      715 non-null    int64
 1   hour                    715 non-null    int64
 2   hour_bef_temperature    714 non-null    float64
 3   hour_bef_precipitation  714 non-null    float64
 4   hour_bef_windspeed      714 non-null    float64
 5   hour_bef_humidity       714 non-null    float64
 6   hour_bef_visibility     714 non-null    float64
 7   hour_bef_ozone          680 non-null    float64
 8   hour_bef_pm10           678 non-null    float64
 9   hour_bef_pm2.5          679 non-null    float64
dtypes: float64(8), int64(2)
memory usage: 56.0 KB

In [529]:
test.describe()

,id,hour,hour_bef_temperature,hour_bef_precipitation,hour_bef_windspeed,hour_bef_humidity,hour_bef_visibility,hour_bef_ozone,hour_bef_pm10,hour_bef_pm2.5
count,715.000000,715.000000,714.000000,714.000000,714.000000,714.000000,714.000000,680.000000,678.000000,679.000000
mean,1056.854545,11.472727,23.263305,0.051821,2.388515,56.668067,1359.494398,0.041196,36.930678,24.939617
std,625.574471,6.928427,4.039645,0.221820,1.171270,19.661880,614.171870,0.020656,12.641503,10.075857
min,0.000000,0.000000,14.600000,0.000000,0.000000,16.000000,126.000000,0.003000,9.000000,7.000000
25%,507.000000,5.500000,20.300000,0.000000,1.500000,42.000000,807.250000,0.027000,28.000000,17.000000
50%,1046.000000,11.000000,22.900000,0.000000,2.300000,55.000000,1489.000000,0.039000,35.000000,24.000000
75%,1616.500000,17.000000,26.375000,0.000000,3.275000,73.750000,2000.000000,0.052250,45.000000,31.000000
max,2177.000000,23.000000,33.800000,1.000000,5.900000,100.000000,2000.000000,0.138000,94.000000,69.000000

In [530]:
train.shape, test.shape

((1459, 11), (715, 10))

In [531]:
# train 결측값 여부 확인
train.isnull().sum()

id                          0
hour                        0
hour_bef_temperature        2
hour_bef_precipitation      2
hour_bef_windspeed          9
hour_bef_humidity           2
hour_bef_visibility         2
hour_bef_ozone             76
hour_bef_pm10              90
hour_bef_pm2.5            117
count                       0
dtype: int64

In [532]:
# test 결측값 여부 확인
test.isnull().sum()

id                         0
hour                       0
hour_bef_temperature       1
hour_bef_precipitation     1
hour_bef_windspeed         1
hour_bef_humidity          1
hour_bef_visibility        1
hour_bef_ozone            35
hour_bef_pm10             37
hour_bef_pm2.5            36
dtype: int64

In [533]:
# 회귀는 주로 standard 를 사용

from sklearn.preprocessing import RobustScaler

robustscaler = RobustScaler()
# robustscaler.fit(train_x)
#train데이터 스케일링
# X_train_robust = robustscaler.transform(X_train) 
# #test데이터 스케일링
# X_test_robust= robustscaler.transform(X_test)

#### 데이터 전처리

In [534]:
# 불필요한 행 삭제

train = train.drop('id', axis = 1)
test = test.drop('id', axis = 1)
train.head()

,hour,hour_bef_temperature,hour_bef_precipitation,hour_bef_windspeed,hour_bef_humidity,hour_bef_visibility,hour_bef_ozone,hour_bef_pm10,hour_bef_pm2.5,count
0,20,16.3,1.0,1.5,89.0,576.0,0.027,76.0,33.0,49.0
1,13,20.1,0.0,1.4,48.0,916.0,0.042,73.0,40.0,159.0
2,6,13.9,0.0,0.7,79.0,1382.0,0.033,32.0,19.0,26.0
3,23,8.1,0.0,2.7,54.0,946.0,0.040,75.0,64.0,57.0
4,18,29.5,0.0,4.8,7.0,2000.0,0.057,27.0,11.0,431.0

In [535]:
# 결측치가 8개 이상인 경우 삭제
train.dropna(thresh=8, inplace= True)
train.isnull().sum()

hour                       0
hour_bef_temperature       0
hour_bef_precipitation     0
hour_bef_windspeed         6
hour_bef_humidity          0
hour_bef_visibility        0
hour_bef_ozone             7
hour_bef_pm10             21
hour_bef_pm2.5            48
count                      0
dtype: int64

In [536]:
# test.dropna(thresh=8, inplace= True)
# test.isnull().sum()

In [537]:
# train 결측치 처리

# train['hour_bef_windspeed'].fillna(train['hour_bef_windspeed'].median(), inplace=True) # 평균 풍속은 중앙값으로 대체
# train['hour_bef_ozone'].fillna(train['hour_bef_ozone'].mean(), inplace=True) # 오존 : 중앙값으로 대체 

# train.isnull().sum(), train.shape

In [538]:
# test 결측치 처리

# test['hour_bef_ozone'].fillna(test['hour_bef_ozone'].mean(), inplace=True) # 오존 : 중앙값으로 대체 

# test.isnull().sum(), test.shape

In [539]:
#KNN imputer 이용해 결측치 대체

from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors = 5) 
train_x = imputer.fit_transform(train)
train_x = pd.DataFrame(train_x, columns=train.columns)

test_x = imputer.fit_transform(test)
test_x = pd.DataFrame(test_x, columns=test.columns)

train_x.isnull().sum(), test_x.isnull().sum()

(hour                      0
 hour_bef_temperature      0
 hour_bef_precipitation    0
 hour_bef_windspeed        0
 hour_bef_humidity         0
 hour_bef_visibility       0
 hour_bef_ozone            0
 hour_bef_pm10             0
 hour_bef_pm2.5            0
 count                     0
 dtype: int64,
 hour                      0
 hour_bef_temperature      0
 hour_bef_precipitation    0
 hour_bef_windspeed        0
 hour_bef_humidity         0
 hour_bef_visibility       0
 hour_bef_ozone            0
 hour_bef_pm10             0
 hour_bef_pm2.5            0
 dtype: int64)

In [540]:
X_train_scaled=robustscaler.fit_transform(train_x)
X_test_scaled=robustscaler.fit_transform(test_x)

X_train_scaled = pd.DataFrame(X_train_scaled, columns=train.columns)
X_test_scaled = pd.DataFrame(X_test_scaled, columns=test.columns)

# X_train_robust = robustscaler.transform(train_x) 
# test데이터 스케일링
# X_test_robust= robustscaler.transform(test_x)

In [541]:
X_train_scaled = X_train_scaled.drop(['count'],axis=1)

# train_x=train_x.drop(['count'], axis=1)

In [542]:
X_test_scaled

,hour,hour_bef_temperature,hour_bef_precipitation,hour_bef_windspeed,hour_bef_humidity,hour_bef_visibility,hour_bef_ozone,hour_bef_pm10,hour_bef_pm2.5
0,-0.347826,-0.363636,0.0,-0.555556,0.222222,-0.442300,0.120482,0.5625,0.214286
1,0.521739,1.173554,0.0,1.722222,-0.698413,0.091481,0.923695,0.8750,0.857143
2,0.173913,-0.644628,1.0,-0.111111,1.269841,-1.080990,-0.722892,0.0625,0.285714
3,-0.434783,-0.066116,0.0,0.111111,0.158730,-0.248426,-0.441767,1.0625,1.000000
4,0.956522,-1.371901,1.0,0.611111,1.206349,-1.060008,0.120482,-1.0625,-0.642857
...,...,...,...,...,...,...,...,...,...
710,-0.869565,0.280992,0.0,0.055556,0.158730,0.221569,0.401606,-0.1500,-0.128571
711,-0.869565,-0.793388,0.0,-0.722222,0.000000,0.435585,0.072289,-0.2125,-0.414286
712,-0.173913,0.066116,0.0,0.000000,0.349206,0.258498,-0.722892,-1.1250,-0.642857
713,0.434783,0.677686,0.0,-0.388889,-0.285714,0.398657,-0.240964,0.3125,0.142857
714,-0.260870,-0.099174,0.0,-0.722222,0.253968,-0.171213,-1.244980,-0.3125,0.000000

In [543]:
from sklearn.model_selection import train_test_split

In [544]:
# 학습 데이터와 테스트 데이터 분리
# 타겟의 구성 비율에 맞게 학습용, 테스트용 검증용 테이터 셋 준비 (data, target random_state, strtify=target)

train_y=train['count']
X_train_scaled, val_x, train_y, val_y = train_test_split(X_train_scaled, train_y, test_size=0.25, random_state=42)

In [545]:
rf = RandomForestRegressor(random_state=11)
rf.fit(X_train_scaled, train_y)

RandomForestRegressor(random_state=11)

In [546]:
y_pred = rf.predict(val_x)
# 예측 라벨과 실제 라벨 사이의 정확도 측정

mean_squared_error(y_pred, val_y)
r2_score(y_pred, val_y)

# 0.7012686805181497

0.7012686805181497

In [547]:
# sgdRegressor = 회귀분석과 동일하지만, 경사하강법을 이용하는것이 특징. 하이퍼파라미터가 존재함.
# from sklearn.model_selection import KFold, GridSearchCV

r = rf.predict(X_test_scaled)

len(r)

715

In [551]:
sub = pd.read_csv('C:/Users/USER/Desktop/poweruser_python/submission.csv')

sub["count"]=pd.Series(r)

In [552]:
sub

       id   count
0       0   95.41
1       1  280.06
2       2   22.80
3       4   62.20
4       5   57.14
..    ...     ...
710  2148   43.51
711  2149   24.40
712  2165   94.39
713  2166  194.54
714  2177  106.67

[715 rows x 2 columns]

In [554]:

sub.to_csv('sub_rumi.csv', index=False)